ecommerse/urls.py
"""
URL configuration for ecommerse project.

The `urlpatterns` list routes URLs to views_docentes. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views_docentes
    1. Add an import:  from my_app import views_docentes
    2. Add a URL to urlpatterns:  path('', views_docentes.home, name='home')
Class-based views_docentes
    1. Add an import:  from other_app.views_docentes import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from ecommerse.viewsIndex import IndexTemplate


urlpatterns = [
    path('', IndexTemplate.as_view()),
    path('docentes/', include('modulos.Docentes.urls')),
    path('actividad/', include('modulos.Actividades.urls')),
    path('login_mod/', include('modulos.Login.urls')),
]

modulos/Actividades/urls.py
from django.urls import path
from modulos.Actividades.views_actividades.view_actividades import anadirActividad

app_name = 'actividad'

urlpatterns = [
    path('crear_actividad/', (anadirActividad.as_view()), name='crear_actividad')
]

modulos/Docentes/urls.py
"""
URL configuration for ecommerse project.

The `urlpatterns` list routes URLs to views_docentes. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views_docentes
    1. Add an import:  from my_app import views_docentes
    2. Add a URL to urlpatterns:  path('', views_docentes.home, name='home')
Class-based views_docentes
    1. Add an import:  from other_app.views_docentes import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.urls import path
from modulos.Docentes.views_docentes.views_docentes import *

app_name = 'docentes'
urlpatterns = [
    path('crear_docente/', (anadirDocente.as_view()), name='agregar_docente'),
    path('editar_docente/<int:pk>', (EditarDocente.as_view()), name='editar_docente'),
    path('eliminar_docente/<int:pk>', (EliminarDocente.as_view()), name='eliminar_docente'),
]

modulos/Login/urls.py
from django.urls import path
from modulos.Login.views_login.views_login import MostrarLogin

app_name = 'login_mod'
urlpatterns = [
    path('login/', (MostrarLogin.as_view()), name='login_view')

]

modulos/Actividades/models.py
from django.db import models
from django.utils.timezone import now

# Create your models here.
class ActividadModel(models.Model):
    nombre_actividad = models.CharField(max_length=50)
    fecha_inicio = models.DateTimeField(default=now)
    fecha_fin = models.DateTimeField(default=None)
    num_horas = models.IntegerField(default=0)

modulos/Docentes/models.py
from django.db import models

class DocentesModel(models.Model):
    nombre = models.CharField(max_length=40)
    apellido = models.CharField(max_length=40)
    correo = models.CharField(max_length=100)

modulos/Login/models.py
from django.db import models

# Create your models here.

modulos/Actividades/forms.py
from django import forms
from django.forms import ModelForm
from modulos.Actividades.models import ActividadModel


class FormActividades(ModelForm):
    class Meta:
        model = ActividadModel
        fields = '__all__'
        widgets = {
            'nombre_actividad': forms.TextInput(attrs={'class': 'form-control', 'id': 'nombreActividad'}),
            'fecha_inicio': forms.DateInput(format=('%Y-%m-%d'), attrs={'class': 'form-control', 'type': 'date', 'id': 'fechaInicio'}),
            'fecha_fin': forms.DateInput(format=('%Y-%m-%d'), attrs={'class': 'form-control', 'type': 'date', 'id': 'fechaFin'}),
            'num_horas': forms.NumberInput(attrs={'class': 'form-control', 'id': 'numHoras'}),

        }

modulos/Docentes/forms.py
from django import forms
from django.forms import ModelForm
from modulos.Docentes.models import DocentesModel


class FormDocentes(ModelForm):
    class Meta:
        model = DocentesModel
        fields = '__all__'
        widgets = {
            'nombre': forms.TextInput(attrs={'class': 'form-control', 'id': 'nombreDocente'}),
            'apellido': forms.TextInput(attrs={'class': 'form-control', 'id': 'apellidoDocente  '}),
            'correo': forms.TextInput(attrs={'class': 'form-control', 'id': 'correoDocente'})

        }

templates/FormTemplate.html
{% extends 'index.html' %}
{% load static %}

{% block main %}


    <div class="mx-5">
        <form class="container text-dark" method="POST" action="{{ action_save }}" id="formulario"
              enctype="multipart/form-data">
            {% csrf_token %}
            <div class="card card-primary mt-5">
                <div class="card-header bg-black">
                    <h3 class="card-title text-center text-white">
                        {{ titulo_add }}
                    </h3>
                </div>
                <div class="card-body row g-3 mt-1">

                    {% block formulario %}

                    {% endblock %}
                </div>

                {% block boton %}
                    <div class="d-flex justify-content-evenly pb-3">
                        <div>
                            <button type="submit" class="btn btn-success" id="boton-guardar">
                                Guardar registro
                            </button>
                        </div>
                        <div>
                            <a href="{{ url_anterior }}" class="btn btn-danger">
                                Cancelar
                            </a>
                        </div>
                    </div>
                {% endblock %}

            </div>


        </form>
    </div>
    {% block presentar_datos %}

    {% endblock %}
{% endblock %}

templates/index.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Módulo Bitácoras</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/design.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.2.0/fonts/remixicon.css" rel="stylesheet">
</head>
<body>
<div>
    <nav class="navbar navbar-expand-lg" style="background: #1c3247">

        <div class="container">
            {% block NombreModo %}
                <a class="navbar-brand text-white text-center" href="/">Modo Administrador</a>
            {% endblock %}
        </div>


    </nav>
    <nav>
        <div style="background: #FE9900; height: 11px; margin-bottom: 0"></div>
    </nav>

</div>
<div class="container d-flex">
    {% block main %}
        <div class="container d-flex justify-content-evenly mt-4">
            <div class="card px-2 py-2" style="width: 16rem;">
                <a href="{% url 'docentes:agregar_docente' %}">
                    <img src="{% static 'img/Docente.png' %}" class="card-img-top" alt="Icono Docente">
                    <div class="card-body">
                        <p class="card-text text-center fs-5 text-decoration-none">Módulo Docentes</p>
                    </div>
                </a>
            </div>
            <div class="card px-2 py-2" style="width: 16rem;">
                <img src="{% static 'img/Actividades.png' %}" class="card-img-top" alt="Icono Actividades">
                <div class="card-body">
                    <a href="{% url 'actividad:crear_actividad' %}">
                        <p class="card-text text-center fs-5"> Módulo Actividades </p>
                    </a>
                </div>
            </div>
            <div class="card px-2 py-2" style="width: 16rem;">
                <img src="{% static 'img/Bitácora.png' %}" class="card-img-top" alt="Icono Bitacora">
                <div class="card-body">
                    <p class="card-text text-center fs-5">Módulo Bitácora</p>
                </div>
            </div>
        </div>
    {% endblock %}
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
<footer class="text-center fixed-bottom text-lg-start footer text-white" style="background: #1c3247">
    <h5 class="texto p-3">Universidad Estatal de Milagro - Todos los derechos reservados - UNEMI 2023</h5>
</footer>


</body>
</html>